const $=s=>document.querySelector(s); const video=$('#camera'), start=$('#start'), game=$('#game'), finish=$('#finish');
const wordEl=$('#word'), trayEl=$('#tray'), msg=$('#msg'), cursor=$('#cursor'), ghost=$('#heldGhost');
const scoreEl=$('#score'), roundNo=$('#roundNo'), totalEl=$('#roundTotal'), finalScore=$('#finalScore');
totalEl.textContent=WORDS.length;
let order=[...WORDS.keys()], idx=0, score=0, held=null, hoverTile=null, hoverStart=0, sx=innerWidth/2, sy=innerHeight/2, lastSeen=0, canAutoDrop=true;
let current=null;
function speak(t){ try{ speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t); u.lang='th-TH'; u.rate=.9; speechSynthesis.speak(u);}catch(e){} }
function shuffle(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1])}
function startGame(){ order=shuffle([...WORDS.keys()]); idx=0; score=0; scoreEl.textContent=0; start.classList.add('hidden'); finish.classList.add('hidden'); game.classList.remove('hidden'); loadWord(); initCamera(); }
function restart(){ startGame(); }
$('#startBtn').onclick=startGame; $('#restartBtn').onclick=restart;
function loadWord(){ current=JSON.parse(JSON.stringify(WORDS[order[idx]])); roundNo.textContent=idx+1; wordEl.innerHTML=''; trayEl.innerHTML=''; held=null; ghost.classList.add('hidden'); msg.textContent='ชี้ค้างที่ตัวอักษร 0.3 วินาที แล้วลากไปใกล้ช่อง';
 current.parts.forEach((p,i)=>{ const c=document.createElement('div'); c.className='cell '+(p.blank?'slot':'fixed'); c.dataset.i=i; c.dataset.answer=p.t; c.dataset.marks=p.marks||''; if(p.blank){c.innerHTML='<span class="base"></span>'+ (p.marks?`<span class="mark">${p.marks}</span>`:'');} else {c.innerHTML=`<span class="base">${p.t}</span>`+(p.marks?`<span class="mark">${p.marks}</span>`:'');} wordEl.appendChild(c); });
 shuffle(current.choices).forEach((ch,i)=>{ const t=document.createElement('div'); t.className='tile'; t.textContent=ch; t.dataset.ch=ch; t.dataset.id='t'+i; trayEl.appendChild(t); });
}
function nearestSlot(x,y){ let best=null, bd=1e9; document.querySelectorAll('.slot').forEach(s=>{ const r=s.getBoundingClientRect(); const cx=r.left+r.width/2, cy=r.top+r.height/2; const d=Math.hypot(x-cx,y-cy); if(d<bd){bd=d;best=s;} }); return bd<115?best:null; }
function clearNear(){ document.querySelectorAll('.slot.near').forEach(s=>s.classList.remove('near')); }
function pickTile(tile){ if(!tile || tile.classList.contains('used'))return; held={ch:tile.dataset.ch, from:tile}; tile.classList.add('used'); ghost.textContent=held.ch; ghost.classList.remove('hidden'); msg.textContent='นำไปใกล้ช่องวาง ระบบจะวางให้ทันที'; canAutoDrop=false; setTimeout(()=>canAutoDrop=true,220); }
function pickFromSlot(slot){ const base=slot.querySelector('.base'); if(!base.textContent)return; held={ch:base.textContent, fromSlot:slot}; base.textContent=''; slot.classList.remove('filled','wrong'); ghost.textContent=held.ch; ghost.classList.remove('hidden'); msg.textContent='ย้ายไปช่องใหม่ได้เลย'; canAutoDrop=false; setTimeout(()=>canAutoDrop=true,220); }
function dropTo(slot){ if(!held||!slot||!canAutoDrop)return; const base=slot.querySelector('.base'); if(base.textContent){return;} base.textContent=held.ch; slot.classList.add('filled'); const ok=held.ch===slot.dataset.answer; if(!ok) slot.classList.add('wrong'); if(held.from && !ok){ /* keep tile used while placed wrong; can move from slot */ } ghost.classList.add('hidden'); held=null; msg.textContent=ok?'วางแล้วค่ะ ⭐':'วางผิด ย้ายไปช่องใหม่ได้ค่ะ'; checkComplete(); }
function returnHeld(){ if(held?.from) held.from.classList.remove('used'); held=null; ghost.classList.add('hidden'); msg.textContent='ตัวอักษรกลับถาดแล้ว'; }
function checkComplete(){ const slots=[...document.querySelectorAll('.slot')]; if(!slots.every(s=>s.querySelector('.base').textContent))return; const ok=slots.every(s=>s.querySelector('.base').textContent===s.dataset.answer); if(ok){ score++; scoreEl.textContent=score; msg.textContent='ถูกต้อง: '+current.full; speak(current.full); setTimeout(()=>{ idx++; if(idx>=order.length){game.classList.add('hidden'); finish.classList.remove('hidden'); finalScore.textContent=score+' / '+WORDS.length; speak('เก่งมากค่ะ');} else loadWord();},1200); } else msg.textContent='ยังมีบางตำแหน่งผิด ลองย้ายใหม่ค่ะ'; }
function updatePointer(x,y){ cursor.style.left=x+'px'; cursor.style.top=y+'px'; if(held){ ghost.style.left=x+'px'; ghost.style.top=y+'px'; const ns=nearestSlot(x,y); clearNear(); if(ns) ns.classList.add('near'); if(ns) dropTo(ns); return; }
 const el=document.elementFromPoint(x,y); if(el!==hoverTile){hoverTile=el; hoverStart=Date.now(); return;} if(Date.now()-hoverStart>300){ if(el?.classList?.contains('tile')){pickTile(el); hoverStart=Date.now()+9999;} else if(el?.classList?.contains('slot')){pickFromSlot(el); hoverStart=Date.now()+9999;} }
}
async function initCamera(){ if(window._camStarted)return; window._camStarted=true; const hands=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`}); hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.72,minTrackingConfidence:.72}); hands.onResults(res=>{ if(res.multiHandLandmarks?.length){ lastSeen=Date.now(); const tip=res.multiHandLandmarks[0][8]; const x=(1-tip.x)*innerWidth, y=tip.y*innerHeight; sx=sx*.68+x*.32; sy=sy*.68+y*.32; updatePointer(sx,sy); } else { clearNear(); if(held && Date.now()-lastSeen>700) returnHeld(); msg.textContent='ยกมือให้อยู่ในกล้องชัด ๆ'; }}); const cam=new Camera(video,{onFrame:async()=>hands.send({image:video}),width:1280,height:720}); cam.start(); }
window.addEventListener('resize',()=>{sx=innerWidth/2;sy=innerHeight/2});
