let words = WORDS.map(w => ({...w, answers:[...w.answers], choices:[...w.choices]}));
let index=0, score=0, selected=null, hoverTarget=null, hoverStart=0;
let smoothX=window.innerWidth/2, smoothY=window.innerHeight/2;
const wordBox=document.getElementById('wordBox'), lettersBox=document.getElementById('lettersBox'), cursor=document.getElementById('cursor'), message=document.getElementById('message'), scoreEl=document.getElementById('score'), progress=document.getElementById('progress'), nextBtn=document.getElementById('nextBtn');
function speak(t){ try{ speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t); u.lang='th-TH'; u.rate=.9; speechSynthesis.speak(u);}catch(e){} }
function loadWord(){ selected=null; hoverTarget=null; hoverStart=0; wordBox.innerHTML=''; lettersBox.innerHTML=''; if(index>=words.length){ progress.textContent='จบเกม'; message.textContent='จบเกมแล้ว คะแนนรวม '+score; speak('เก่งมาก จบเกมแล้ว'); return; } const item=words[index]; const ans=[...item.answers]; progress.textContent=`คำที่ ${index+1}/${words.length}`; item.show.forEach(ch=>{ const div=document.createElement('div'); if(ch==='_'){div.className='slot';div.dataset.answer=ans.shift();}else{div.className='fixed';div.textContent=ch;} wordBox.appendChild(div); }); item.choices.sort(()=>Math.random()-.5).forEach(ch=>{ const div=document.createElement('div'); div.className='letter'; div.textContent=ch; lettersBox.appendChild(div); }); message.textContent='เติมคำให้ถูกต้อง'; }
function elementAt(x,y){ cursor.style.display='none'; const el=document.elementFromPoint(x,y); cursor.style.display='block'; return el; }
function resetLetter(el){ el.classList.remove('holding'); el.style.left=''; el.style.top=''; el.style.position=''; el.style.zIndex=''; }
function nextWord(){ index++; loadWord(); }
nextBtn.onclick=nextWord;
function pickOrDrop(x,y){ const el=elementAt(x,y); if(!el) return; if(el!==hoverTarget){ hoverTarget=el; hoverStart=Date.now(); return;} if(Date.now()-hoverStart<620) return; if(!selected && el.classList.contains('letter')){ selected=el; selected.classList.add('holding'); selected.style.position='fixed'; selected.style.zIndex='100'; message.textContent='ถือ: '+selected.textContent; speak(selected.textContent); hoverStart=Date.now()+350; return; } if(selected && el.classList.contains('slot') && !el.textContent){ if(selected.textContent===el.dataset.answer){ el.textContent=selected.textContent; el.classList.add('filled','celebrate'); selected.remove(); selected=null; score++; scoreEl.textContent=score; message.textContent='เก่งมากค่ะ ⭐'; speak('เก่งมากค่ะ'); if([...document.querySelectorAll('.slot')].every(s=>s.textContent)){ setTimeout(()=>{ message.textContent='ถูกต้อง คำว่า '+words[index].full; speak(words[index].full); setTimeout(nextWord,1500); },400); } }else{ message.textContent='ยังไม่ถูก ลองใหม่นะ'; speak('ลองใหม่'); resetLetter(selected); selected=null; } hoverStart=Date.now()+450; } }
function updateSelected(x,y){ if(selected){ selected.style.left=(x-selected.offsetWidth/2)+'px'; selected.style.top=(y-selected.offsetHeight/2)+'px'; } }
loadWord();
const videoElement=document.getElementById('video');
const hands=new Hands({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`});
hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.78,minTrackingConfidence:.78});
hands.onResults(results=>{ if(results.multiHandLandmarks && results.multiHandLandmarks.length){ const tip=results.multiHandLandmarks[0][8]; const x=(1-tip.x)*window.innerWidth, y=tip.y*window.innerHeight; smoothX=smoothX*.72+x*.28; smoothY=smoothY*.72+y*.28; cursor.style.left=smoothX+'px'; cursor.style.top=smoothY+'px'; updateSelected(smoothX,smoothY); pickOrDrop(smoothX,smoothY); }else{ message.textContent='ยกมือให้อยู่ในกล้องชัด ๆ'; } });
const camera=new Camera(videoElement,{onFrame:async()=>{await hands.send({image:videoElement});},width:1280,height:720});
camera.start().catch(()=>{message.textContent='กรุณาอนุญาตใช้กล้องก่อน';});
